name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Google Cloud SDK
      uses: google-github-actions/setup-gcloud@main
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: quash-v1
        export_default_credentials: true

    - name: Configure .env files
      run: |
        if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
          cp .env.production .env.local
        elif [[ "${{ github.ref }}" == "refs/heads/develop" ]]; then
          cp .env.staging .env.local
        fi

    - name: Build and Deploy to Cloud Run
      run: |
        # Determine the service name based on the branch
        SERVICE_NAME="quash-dashboard-services"  # default to production service
        if [[ "${{ github.ref }}" == "refs/heads/develop" ]]; then
          SERVICE_NAME="quash-dashboard-develop"
        fi

        # Write the service account key to a file
        echo "${{ secrets.GCP_SA_KEY }}" | base64 -d > sa_key.json
        # Authenticate gcloud CLI with the service account key
        gcloud auth activate-service-account --key-file=sa_key.json
        # Authenticate Docker with GCR
        gcloud auth configure-docker

        # Build and push the Docker image
        docker build -t gcr.io/quash-v1/$SERVICE_NAME:${{ github.sha }} .
        docker push gcr.io/quash-v1/$SERVICE_NAME:${{ github.sha }}

        # Deploy to the respective Cloud Run service
        gcloud run deploy $SERVICE_NAME --image gcr.io/quash-v1/$SERVICE_NAME:${{ github.sha }} --platform managed --region asia-south1

        # Cleanup
        rm sa_key.json